version: '3.3'
services:
  postgres:
    image: postgres:15
    container_name: textdys
    ports:
     - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ${PWD}/db:${PWD}/db
  redis:
    image: redis:7
    ports:
      - '127.0.0.1:6379:6379'
    container_name: redis_textdys
